name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS1 }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
                    # Asegúrate de que PM2 esté instalado
                    if ! command -v pm2 &> /dev/null; then
                    echo "PM2 no está instalado. Instalando..."
                    sudo npm install -g pm2
                    fi
                    
                    # Detener y eliminar la aplicación si ya está en ejecución
                    pm2 delete my-app || echo "No existing process found"
                    
                    # Navegar al directorio de la aplicación
                    cd ${{ secrets.TARGET_DIR }}
            
            # Instalar Node.js
                    echo "Instalando Node.js..."
                    curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
                    sudo yum install -y nodejs
            
            # Actualizar el código desde el repositorio
                    echo "Actualizando el código desde el repositorio..."
                    sudo git pull origin main
            
            # Instalar dependencias
                    echo "Instalando dependencias..."
                    sudo npm install
            
            # Construir la aplicación (si es necesario)
                    echo "Construyendo la aplicación..."
                    sudo npm run build
            
            # Iniciar la aplicación con PM2 usando node app.js
                    echo "Iniciando la aplicación con PM2..."
                    sudo pm2 start node --name "my-app" -- app.js
            
            # Guardar el estado de PM2
                    sudo pm2 save
            
            # Encuentra el PID del proceso que está usando el puerto 3000
                    PID=$(lsof -t -i:3000)
            
            # Verifica si se encontró un proceso
                    if [ -n "$PID" ]; then
                    echo "Deteniendo el proceso que está usando el puerto 3000 (PID: $PID)..."
            # Detener el proceso
                    kill -9 $PID
                    echo "Proceso detenido."
                    else
                    echo "No hay ningún proceso usando el puerto 3000."
                    fi
            
            # Iniciar la aplicación en segundo plano
                    cd web_distribuida
                    sudo node app.js > app.log 2>&1 &
                    
                    echo "La aplicación se está ejecutando en segundo plano." ```yaml
                    echo "La aplicación se está ejecutando en segundo plano."